### ISSUE TITLE
Recuperar el archivo de Firmas

### ISSUE THREAD

**Issue by JuliaBonsignore** [inkua/Website#17]
Antes de actualizar el sitio web el modelo de firmas para mails estaba en este enlace: 
https://inkua.de/prueba/firma/firma-inkua.html

Luego de que se actualice ya no se puede acceder. Probablemente se haya cambiado de lugar el archivo.

**Comment by frankinkua** [comment]
Me pongo a trabajar en esto. Seguro lo encuentro en algún backup.

**Comment by JuliaBonsignore** [comment]
Perfecto, muchas gracias!
